import { HttpEvent, HttpHandler, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';


@Injectable()
export class HeadersInterceptor implements HttpInterceptor {

  constructor(){}

  intercept( req: HttpRequest<any>, next: HttpHandler ): Observable<HttpEvent<any>> {

    //Verificar el tipo de peticion (por el momento)
    if (req.method === 'POST'){

      //Verificar de donde vendrán estos valores
      const authorizationHeader = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MDYzNjc5MTQsImlhdCI6MTcwNjM2NzkxNCwic3ViIjoibkcxRUxUT1ZneUlvRktEQkFSeURhdzloSmVvMlF4WTZzM29qay95ckZaNXVOSUxWNllodU1zMjBNSmt0a2dYNk04R280ZHVxc0dVUG44S1dOUjlaaXVJakhXYWFNOVVkNmFTK1p0K2hQdnFGcFVGWk8rSHovSnNLN2UyVTlnQ09SN2orRkhaSDhsZzJ3dFQydXlHTUFTMVdMaEdCYWhZOFZHQytVeWl3akNLd2JRWE1rL0Q0M1BXODY4a2FKK3pvMUF1SmFiVXdnMC8zOVVTbGFkLzFBem1kSHlUa29KWTZmVWR4c0I2cDFzdkc5Vmk5eHUyQ2c3TVJHRTFZSXRLRytlcmMwODRvMHFZWUJoemk4aWVnUDhqSWRpd1U2UDJOcS8yQ0QyYnArWi9ablpvd284VTVvb3pid0QzMWZSUjFrTHNKRzdGQy94eHdmRklzRW1WYUhRPT0iLCJ1c2VyIjoiaUNmUmJiWTdPRnVxWTVoSkVPcWhxSVlwV3JOaWMrK2Z3bWM5aFJCUFNaRFZVSS94UDM5bWJCbUdzdzRsLzdhelIvM3M2Vlc2NThjUGdGcWp6ZnBDaFRoUjRhdDg2b0E2QVNvS1RtdkVwSVpwYXdNSWFNdGxwNklCa291bnFZYTkrbkZDREx2M1dOckpsR3kzZkFLNjJFM0E5SGV5cmNZejR5TUcvNFllVVdKTm5Db3ByNkcybzdMOTh5aUtHZWwxOHp1RTRXOXVxckhaT1RQblAybXp6ZDBiUWZDeDlKelZUcjFkV1VhQ2xTdFJidzNPNFZ2cS9BYit2elBFRXcvMVBmek1SWDBxSjU4TGpzV0dNenMyc1dtRHBnZWJ4SFB0TDdFeG5Kb3NkRFhnUXZCcWJkcmZLcG5XZGRTRWZKKzB3bHlaQjAraEZzQmF0TCtZR0M1anNBPT0iLCJ0ZXJtaW5hbCI6IlFZVXJLYi93aWNHaktPeXFRTTNUbUV2Z1NaeGdIRm1lUDBuKzhlY09hZHBySXZKREV6NjMvY1hGK283QlNHLzNzNFMxTEIxcXpCdkpqV3BKRGM1NVp0Sm1ZVVkyVTIrQ25RY3hVZHI3RzczMDE1VWM0SmZoVVd2RU1SSUxJck1vZEIyOWZrZ2JWcHM5eW1MWFI4ckRqMW1QTTZxU0RVK2w3YjVRU29uUFE0TmNwbms0QkVsSGN3MUUrclZ0Slh2aFE2eDN3ZXRJc2RSRjlBRUU5RWhRakE2UXZhMGw5L0pmNGxWRGVaTHRmUzljMlZVVkJLbkZhdHJxcmo1MjN3YldKNktHZ1IvUk1LM0gvY3BpcVJoRVNBZTA1andWYkFFelNEZlRKUEVvS3llbkRrVTdnRDhLdWdQSmd2eC9nYnlkeW9TMk56alhkNjZnbkdjQkN1aU5FQT09IiwiYXBwbGljYXRpb24iOiJJNEt1bU5rNERKRHhvSlZ6cXhET2lVbWVCODN1TUNCemNxSWEyZlpuamNXVjJKbmdVQ3R5QThyMndxT0hxVEpxcnorU3VYeDFpcXJ4MCtINlFBSnhKRWR2MmhXMWp4Q2YrR0RIUjM3a0JIVllNUlRiRkZmRzRyOEtIeWdJc2c3TVFuNjZxVCtmRkNPbGlUK0hjNWQxbVl5YTJiK2ZkblZNaEJoQlFuSWsvZ1FJRzRKSnJpSUt6Z2FoZHd4VlI2bm8xUTcvS01wSUdIT0lzNFEzanlxSWlLbTVsSVErV0hJbkJyMGE4aHBvMjd1VUtOL2w4UFJ5ZXZtcjJkUUxCeTVXK1c2RVlWUFcxVGQvM1R2NFdJY3Zrb1lIS05ETWJUMFIyNmZGaFRUOG1LRXc0NnNvOWh6UEJad3RJZTlNcDNMZk41N2RDdTJaZHBaUi9LSVNpeFIvd2c9PSIsImV4cCI6MTcwNjQ1NDMxNCwiaXNzIjoicG9zLXNlcnZpY2UifQ.deXVsCnSXLXOq4uxVicziN4SzUIGf7zEvungbnOCo0g';
      const terminalHeader = 'jA9ZcRGFxqF4kybHpHOnatGY4QHvmMxDyzN4clDVSsWWqwoBtCyTikYhJIUYRfRqAyVKc5BP4Fa7mLKJdEHznPmlKZGhJfU+pGqzBTisEzKwwYxRstZf/f8bS9YztRsUL9pIFstn7ip1DlCzWGCGrBLT9x3ae2TamKkPX4QSAOAToRQcZsRQyftEe2JxpuB5EHNetdlvDTBvp3BWpJrg0vVx7LQYhHIKLHkUoTxJqO+WFGKZaCGjq3z/8jNfo6tJ5nEzzCDI8hL/hfvfdgK50NSyvUZP1VEKEbrUbIaKqo4dyAumH3uR4ttVMYwUNzb2quyAmLqhcseWgQSKNNyZkw==';
      const userHeader = 'v7LhYvulcPxyvIaF8v2lXnsHVPazSaeSKB2T6GqCoT2B1Gfav8Mm6mGg7ym5d0dcnmzS/Sh9BG+a4boenjEY+8DmoiK/FBz47UcXn9wchkrboL4MdR210r5sxXaIibLL6v30xvyvq9pGPQTrcbYQdME2jROX0n7F2fl+PTN+BOLVE71xHFI4NoMnIDjIuFH1lEftE5FzjSLfa0F7Yy1g3xrNjkL2zi2LWxRArqGetylcs4R9LaMcil9PI/SRFg7J9l9rwMTGmUb7rng/jJVROccEJULOJpbYNARCgq7fK/0e5BSRsyd0OfVvAN3AuA2y7Uxu7cmQpgobb5cv4M/f3w==';

      //clonar la solicitud y agregar los encabezados
      const cloneReq = req.clone({
        setHeaders: {
          'Authorization': authorizationHeader,
          'Terminal': terminalHeader,
          'User': userHeader
        }
      })

      return next.handle( cloneReq );

    }

    //Pasa exactamente igual la petición si no es POST (por el momento)
    return next.handle(req);
    }


}
