// Generated by https://quicktype.io

export interface ByEanResponse {
  codigo:        string;
  descripcion:   string;
  idPlu:         number;
  eanCode:       string;
  quality:       string;
  reference:     string;
  color:         string;
  size:          string;
  quantity:      string;
  referenceName: string;
  price:         number;
  sku:           string;
  stateSku:      string;
  stateSkuName:  string;
  genderId:      string;
  genderName:    string;
}


