// Generated by https://quicktype.io

export interface ByRefResponse {
  codigo:      string;
  descripcion: string;
  items:       Item[];
}

export interface Item {
  parent:           string;
  reference:        string;
  color:            string;
  size:             string;
  presentationSize: string;
  swatch:           string;
  nameColor:        string;
  msg:              string;
  qty:              number;
  name:             string;
  images:           string;
  retailPrice:      number;
  offerPrice:       number;
  barCode:          string;
  sku:              string;
  stateSku:         string;
  stateSkuName:     string;
  genderId:         string;
  genderName:       string;
}
